# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_announcement_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
