# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160311_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
