# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160311_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[(b'STF', b'Staff'), (b'STD', b'Student')], max_length=3),
        ),
    ]
