# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20160311_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='student',
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='upload_quantity',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.DocumentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.DocumentType'),
            preserve_default=False,
        ),
    ]
