# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160313_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='document_type',
        ),
        migrations.AlterField(
            model_name='document',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
