# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160313_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentrequest',
            options={'verbose_name_plural': 'Document Requests'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name_plural': 'User Types'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='upload_quantity',
            field=models.PositiveSmallIntegerField(verbose_name=b'Number Of Files Allowed'),
        ),
    ]
