# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160313_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.DocumentType'),
            preserve_default=False,
        ),
    ]
