# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160314_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc_request',
            new_name='document_request',
        ),
    ]
