# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160314_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name_plural': 'Document Types'},
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=b'documents/%d-%m-%Y'),
        ),
    ]
