# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160314_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.DocumentType'),
            preserve_default=False,
        ),
    ]
