# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='ABC', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=utils.AutoSlugField(blank=True, db_index=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=utils.AutoSlugField(blank=True, db_index=False, populate_from='title'),
        ),
    ]
