# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0002_auto_20160312_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=utils.AutoSlugField(blank=True, db_index=False, editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=utils.AutoSlugField(blank=True, db_index=False, editable=False, populate_from='title'),
        ),
    ]
