# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='comment',
            new_name='description',
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='discuss.Topic'),
            preserve_default=False,
        ),
    ]
